language: android

jdk:
    - openjdk8

android:
  components:
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27
    - build-tools-27.0.3

script: 
    - ./gradlew desktop:dist
